version: 2
updates:
  # 1. Quét npm/yarn packages
  - package-ecosystem: "npm"
    directory: "/CapdeCours" # thư mục gốc
    schedule:
      interval: "weekly" # có thể chọn daily / weekly / monthly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "npm"
    commit-message:
      prefix: "deps"

  # 2. Quét GitHub Actions workflow
  - package-ecosystem: "github-actions"
    directory: "/" # workflows luôn ở root
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "actions"
    commit-message:
      prefix: "ci"
