name: CI

on:
    push:
        branches: [main, dev]
    pull_request:
        branches: [main, dev]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v5

            - name: Setup Node.js
              uses: actions/setup-node@v5
              with:
                  node-version: 20.19.4
                  cache: "npm"
                  cache-dependency-path: demo-app/package-lock.json

            - name: Install dependencies
              run: npm ci
              working-directory: demo-app

            - name: Lint
              run: npm run lint
              working-directory: demo-app
